% Set default properties globally
FS = 12;
set(0, 'DefaultTextInterpreter', 'latex', ...
       'DefaultAxesTickLabelInterpreter', 'latex', ...
       'DefaultLegendInterpreter', 'latex', ...
       'DefaultAxesFontSize', FS, ...
       'DefaultTextFontSize', FS);