% Generate Figure 18 for the paper
%    S. Weiss, S.J. Schlecht, and M. Moonen: "Best Least Squares Paraunitary 
%    Approximation of Matrices of Analytic Functions," submitted to IEEE 
%    Trans. Signal Process., submitted Mar. 2025.
%
% Plot results for an ensemble simulation with different matrix dimensions.
% The results are read in from a text file, which is generated by the scripts
% ProcrustesLargeMatrixEnsembleTest.m, which calls
% ProcrustesLargeMatrixSingleTest.m.

clear all; close all;

%-------------------------------------------------------------------------------
% read in results generated by ProcrustesLargeMatrixEnsenbleTest.m
%-------------------------------------------------------------------------------
Res = dlmread('LargeMatrixEnsembleResults.txt');

% instances with problems (these outliers fall outside the considered 
% percentiles):
%  93,32,4096,4096,0.00026977,35.062,43.1
%  10,64,32768,10017,2.8355e-11,64.691,402.89
%  40,64,4096,4096,5.0618e-09,93.566,102.62
%  55,64,16384,3561,1.0202e-11,59.358,177.2

%-------------------------------------------------------------------------------
% evaluate statistics --- median and 90% percentiles
%-------------------------------------------------------------------------------
M = [2, 4, 8, 16, 32, 64, 96];
R = zeros(length(M),12);
% the following only works if all M have the same number of results N
N = 100;
Stats = zeros(12,length(M));
for k = 1:4,
   Interim = zeros(N,length(M));
   for m = 1:length(M),
      MIndex = find(Res(:,2)==M(m));
      Interim(:,m) = sort(Res(MIndex,k+3));
   end;
   Stats(3*(k-1)+1:3*k,:) = Interim([6; ceil(N/2); 95],:);
end;

%-------------------------------------------------------------------------------
% plot curves
%-------------------------------------------------------------------------------
% for legend only
loglog([1 1],[1 1],'b-'); hold on;
loglog([1 1],[1 1],'r--');
loglog([1 1],[1 1],'k:');
loglog([1 1],[1 1],'-.','color',[0 0.5 0]);
% now the actual curves --- order of Procrustes solution
loglog(M,Stats(2,:)/100,'k:');
errorbar(M,Stats(2,:)/100,(Stats(2,:)-Stats(1,:))/100,...
        (Stats(3,:)-Stats(2,:))/100,'k.');
% paraunitarity error
loglog(M,Stats(5,:)*1e14,'-.','color',[0 0.5 0]);
errorbar(M,Stats(5,:)*1e14,(Stats(5,:)-Stats(4,:))*1e14,...
         (Stats(6,:)-Stats(5,:))*1e14,'.','color',[0 0.5 0]);
% least squares error
loglog(M,Stats(8,:),'b-');
errorbar(0.98*M,Stats(8,:),(Stats(8,:)-Stats(7,:)),(Stats(9,:)-Stats(8,:)),'b.');
% computation time
loglog(M,Stats(11,:),'r--');
errorbar(1.02*M,Stats(11,:),(Stats(11,:)-Stats(10,:)),...
         (Stats(12,:)-Stats(11,:)),'r.');
% labelling etc
set(gca,'TickLabelInterpreter','latex','XTick',M,'XTickLabel',...
    {'$2$','$4$','$8$','$16$','$32$','$64$','$96$'});
axis([1.9 100 0.1 300]);
grid;
legend({'least squares error $e_{\mathrm{LS}}$','computation time $T$/[s]',...
        'order $\mathcal{O}\{\hat{\textbf{\textit{Q}}}(z)\}/100$',...
          'paraunitarity error $e_{\mathrm{PU}} \cdot10^{14}$'},...
        'interpreter','latex','location','NorthWest');
set(gcf,'OuterPosition',[230 250 570 450]);
set(gca,'LooseInset',get(gca,'TightInset'));
xlabel('matrix dimension $M$','interpreter','latex'); 
ylabel('value','interpreter','latex');
print -depsc TSP_PPP_Fig18.eps


