% ProcrustesRandomMatrixEnsembleEval.m
%
% Matlab script file to evaluate the ensemble results for [1]. The results
% in the matrix Res have been imported from the file "EnsembleResults.txt".
%
% [1] S. Weiss, S.J. Schlecht, M. Moonen: "Best Least Squares Paraunitary
%     Approximation of Matrices of Analytic Functions," submitted to IEEE
%     Trans. Signal Process., Mar. 2025.

clear all; close all;

% difficult seed values:
% [508, 686, 752]  
% these required an increased DFT size and lowering the threshold e to 1e-5
%
% [264,  544, 698] 
% these possess two very closely spaced zeros that only make a negligible 
% contribution to the cost function, but result in allpass components that only
% decay very slowly; pruning such zero crossings in PUProcrastes() has removed
% this challenge.

% read in results generated by ProcrustesRandomMatrixEnsenbleTest.m
Res = dlmread('EnsembleResults.txt');

% display ensemble statistics
fprintf('Ensemble paraunitarity error of Procrustes solution:\n');
fprintf('\t%-25s %1.12f\n', 'Mean:', mean(Res(:,5)));
fprintf('\t%-25s %1.12f\n\n', 'Standard deviation:', std(Res(:,5)));

dummy = (Res(:,6) - Res(:,2)) ./ Res(:,2);
fprintf('Normalised least squares mismatch of Procrustes solution:\n');
fprintf('\t%-25s %1.12f\n', 'Mean:', mean(dummy));
fprintf('\t%-25s %1.12f\n\n', 'Standard deviation:', std(dummy));

